version: "3.7"
services:
    app:
        build:
            context: .
            dockerfile: ./docker-compose/php/Dockerfile
        image: tacka-api
        container_name: tacka-api-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - tacka-api-network
        depends_on:
            - mysql
    mysql:
        image: mysql:8
        ports:
            - '${DB_PORT:-3306}:3306'
        container_name: tacka-api-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - tacka-api-mysql-data:/var/lib/mysql
            - ./docker-compose/mysql/dump/:/docker-entrypoint-initdb.d
        networks:
            - tacka-api-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: tacka-api-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: "${DB_HOST}"
            PMA_PORT: "${DB_PORT}"
            PMA_USER: "${DB_USERNAME}"
            PMA_PASSWORD: "${DB_PASSWORD}"
        ports:
            - "8081:80"
        networks:
            - tacka-api-network
    nginx:
        image: nginx:alpine
        container_name: tacka-api-nginx
        restart: unless-stopped
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - ./:/var/www
            - "./storage/public/data:/var/www/public/storage/data:ro"
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - tacka-api-network

networks:
    tacka-api-network:
        driver: bridge
volumes:
    tacka-api-mysql-data:
        driver: local
